resolver: nightly-2021-11-19

extra-deps:
  - {git: "https://github.com/nikita-volkov/fx", commit: "a612390cf54c37150c367324b154170921b98318"}
  - {git: "https://github.com/nikita-volkov/moore-machines", commit: "7e95c33b203a1cfe42dbc0e0de3cec8e6fe94290"}
