resolver: nightly-2021-07-04

extra-deps:
  - acc-0.1.3
  - ascii-string-1.0.1.3
  - attoparsec-data-1.0.5.2
  - attoparsec-time-1.0.1.2
  - domain-0.1.1.2
  - domain-core-0.1
  - domain-optics-0.1.0.1
  - th-lego-0.2.3
  - yaml-unscrambler-0.1.0.3
  - {git: "https://github.com/nikita-volkov/fx", commit: "a612390cf54c37150c367324b154170921b98318"}
  - {git: "https://github.com/nikita-volkov/moore-machines", commit: "7e95c33b203a1cfe42dbc0e0de3cec8e6fe94290"}
  - {git: "https://github.com/nikita-volkov/reduction", commit: "6045f611ae391b750d7f2620d19844394b9e5166"}
