resolver: .stack-snapshot/snapshot.yaml
packages:
  - actor-system
  - coalmine
  - command-event
  - compiles
  - format
  - contextually
  - download
  - easings-dot-net
  - jet
  - lift-instances
  - list-t-optics
  - partial-isomorphism-class
  - posix-path
  - posix-path-classes
  - posix-path-directory
  - posix-path-structures
  - qq-extras
  - resilient-io
  - yashin
