resolver: .stack-snapshot/snapshot.yaml
packages:
  - actor-system
  - coalmine
  - command-event
  - company
  - list-t-optics
  - partial-isomorphism-class
  - posix-path
  - posix-path-classes
  - posix-path-structures
