resolver: nightly-2022-06-08

extra-deps:
  - git: https://github.com/nikita-volkov/moore-machines
    commit: 7e95c33b203a1cfe42dbc0e0de3cec8e6fe94290
  - git: https://github.com/nikita-volkov/isomorphism-class
    commit: 33e2a25e9adeabed528d859c6e4a605062e48437
  - git: https://github.com/nikita-volkov/structure-kit
    commit: f9cc646220ada4cc5e4de0509b8409ab987b92b4
  - aeson-value-parser-0.19.6
  - cereal-unordered-containers-0.1
  - domain-aeson-0.1
  - domain-cereal-0.1
  - jsonifier-0.2.1.1
  - leb128-cereal-1.2
  - vector-extras-0.2.6
